name: C++ Lint with cppcheck

on: [push, pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install cppcheck
      run: sudo apt-get update && sudo apt-get install cppcheck

    - name: Run cppcheck on code files
      run: cppcheck --enable=all --std=c++11 --language=c++ --error-exitcode=1 --suppress=*:main.cpp --suppress=missingIncludeSystem main.cpp